services:
  go-ddd-handson-uitest:
    container_name: go-ddd-handson-uitest
    build: .
    tty: true
    volumes:
      - ./src:/go/src  
    networks:
      - external
networks:
  external:
    name: goweb-exercise-net
    external: true